### ISSUE TITLE
How to implement in evcc?

### ISSUE THREAD

**Issue by thecem** [mabunixda/wattpilot#1]
Is there a describtion, how to implment it to EVCC?

thx!

**Comment by intimber2k** [comment]
Hi, 
I would also love to see some information about how to add this to evcc ;-)

**Comment by mabunixda** [comment]
I am already [on the go](https://github.com/mabunixda/evcc/tree/fronius-wattpilot) ... but stopping the load process when the SOC target is reached does not work at the moment

**Comment by mabunixda** [comment]
And opened [PR](https://github.com/evcc-io/evcc/pull/4291)

**Comment by intimber2k** [comment]
Hi Martin, 
Wäre es möglich, dass du uns ein evcc-Binary zur Verfügung stellst, welches deinen Wattpilot-Code bereits beinhaltet? So könnten wir schonmal testen bis der PR durch und eine neue evcc-Version zur Verfügung gestellt worden ist.
Mein evcc läuft auf derzeit auf Debian, mit einem Windows-Binary könnte ich aber auch arbeiten.
Beste Grüsse, 
Denis

**Comment by mabunixda** [comment]
hi, there is the docker iamge [mabunixda/evcc:testing](https://hub.docker.com/layers/mabunixda/evcc/testing/images/sha256-9f6a6f1564113a44a28debcfa0a56f51b93cde00175c1f02372958e0d78d415e?context=explore) and i upload here the actual binary 
[evcc.zip](https://github.com/mabunixda/wattpilot/files/9479562/evcc.zip)

Be aware that it is not a full functional implementation - stopping the load process does not work at the moment!
