### ISSUE TITLE
Prometheus exporter does not provide nrg data

### ISSUE THREAD

**Issue by chpro** [mabunixda/wattpilot#33]
I stumbled over the project and was happy to see that there is a prometheus exporter which works like a charm. Currently using it to get the data of wattpilot into influxdb for a Grafana dashboard via telegraf. 

The only thing I'm missing are the `nrg` related metrics which are defined here https://github.com/mabunixda/wattpilot/blob/main/wattpilot_mapping.go 

Hope you can help to get these metrics also via prometheus exporter.

Thank you.

**Comment by mabunixda** [comment]
PR is merged and available!
